### PR TITLE
Fix minor calculation error

### PR DESCRIPTION
**Pull request by hyfloac**
Based on the math being used the following statements are true:
`SIN_TABLE[0] = sin(0) = 0;`
`SIN_TABLE[16384] = sin(pi / 2) = 1`
`SIN_TABLE[32768] = sin(pi) = 0`
`SIN_TABLE[49152] = sin(3/2 * pi) = sin((pi / 2) + pi) = 1`
except the last statement should be:
`SIN_TABLE[49152] = sin(3/2 * pi) = sin((pi / 2) + pi) = -1`

### CODE REVIEW

**Comment by hyfloac** [comment]
Also this code already exists in in 1.7.10 and upwards (probably backwards a bit to) in `net.minecraft.util.math.MathHelper`.

**Comment by LordFokas** [comment]
@hyfloac and you'd trust Mojang code? :p

**Comment by hyfloac** [comment]
@LordFokas Seeing as the code is literally the same (with the minor exception of not having the forced definitions every 1/4 of the circle), yes I would. Most of there code is reliable and of the things that aren't I am sure a fair number of them could be blamed on ProGuard obfuscation & optimizations. The only thing I have seen which has been regarded a fairly bad idea was to use BlockPos (which you can read about [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272953-optifine-hd-d1-fps-boost-dynamic-lights-shaders?page=2105#c43757), the basics are extreme memory overhead due to immutable classes and the effect this has on garbage collection).

**Comment by LordFokas** [comment]
BlockPos being immutable is ... meh.
But generally speaking it's better to use a single class than 3 ints.

**Pull request merged**
