### PR TITLE
Add Elements to TabBase

### PR DESCRIPTION
**Pull request by chbachman**
The TabBase now has an array of elements that it can hold. It shifts the coordinates of everything in it to make 0,0 at the top right corner of the tab.

### CODE REVIEW

**Comment by skyboy** [comment]
Can you remove the formatting of classes that have nothing to do with this PR?

**Comment by chbachman** [comment]
Yeah, done. Sorry for the excessive commits, I had trouble removing it.

**Comment by KingLemming** [comment]
Trying to see if I can merge this into a branch and test safely that way.

**Comment by Parker8283** [comment]
You could just pull his repo

**Pull request merged**
