### PR TITLE
More configuration options for lake generator

### PR DESCRIPTION
**Pull request by headprogrammingczar**
There are a few magic numbers that can be made configurable in the lake generator. I also added an optional random offset which combines nicely with the cave generator type and "air lake" pseudo-geodes, making them generate sticking out from the main cave path rather than appearing inline.

### CODE REVIEW

**Comment by headprogrammingczar** [comment]
This PR is dependent on https://github.com/CoFH/CoFHCore/pull/30

**Comment by skyboy** [comment]
I'd merge this if i knew what effect changing the blob size has on the calculations for the *Center variables. The values for that seem to be intentional but I have no idea what they mean or what effect they have, and suspect changing the blob size will require recalculating them.

**Comment by headprogrammingczar** [comment]
The size variables create an AABB of sorts for each blob. The center is calculated based on that to keep the blob's AABB entirely within the generator's AABB. The math looks odd because it's using some manually squared formulas to make the distance calculation lower down more performant.

**Comment by skyboy** [comment]
So they do need rewritten, as some values create negative center positions.

**Comment by KingLemming** [comment]
Everything has changed a ton and we aren't supporting 1.7.10 anymore, but thank you. :)

**Pull request closed without merging**
