### PR TITLE
Added offset for rendering the initial text rendering

### PR DESCRIPTION
**Pull request by Shirkit**

### CODE REVIEW

**Comment by Shirkit** [comment]
So this allows child classes to implement horizontal and vertical centering of the TextField's text. Bringing the centering to this class would imply in major changes due to how its currently written to support both multiline and non-multuline textfields. If not approved, I can then bring the centering code into the class, but I do not know if it's worth at all.

**Comment by skyboy** [comment]
I'm not opposed, however the offset allows the text to appear outside the field entirely in addition to throwing off the calculations for mouse interaction, preventing the user from knowing where to click to interact with the field.

It would probably be better to have the logic for centering the text, but abstracted such that it can be used to left-justify, center, and right-justify on the two axes independently.
The rendering code can manage it easy enough with loop-local variables for startX/Y with offsets applied; a function call to get the offset can take the current index for caching purposes which should be re-usable for the mouse interaction code and the render location code if it needs it.

**Comment by Shirkit** [comment]
Just to clarify, the PR needs to satisfy those requirements, right?

**Comment by skyboy** [comment]
Yes, the logic needs to bound the displayed text to within the textfield, and allow user interaction to be natural, rather than hunting for a distant spot to click.

**Pull request closed without merging**
