### PR TITLE
1.9.4

### PR DESCRIPTION
**Pull request by covers1624**
So after seeing KL's reddit reply saying no one is stepping up to contribute, Tada!
This is very basic and just a compile complete update, im working on Core(done) and Foundation as well.
Foundation seems to be missing some stuff from core, maybe you forgot to push some stuff KL.

Also do you have a formatter i should use?

At this point iv'e updated all of CB's mods and am looking for some more 1.9 work to do.

### CODE REVIEW

**Comment by joekaiser** [comment]
Not that my opinion matter, but I give it a :+1: Maybe I can find time to help out as well

**Comment by skyboy** [comment]
When I get the last 1.7 release together and pushed I'll start dealing with 1.9 and review this properly; In the mean time, can you correct the tabbing of this? You can find the (eclipse) formatter settings here: https://github.com/CoFH/Version/blob/master/Formatter.xml

**Comment by covers1624** [comment]
Totally missed that, sure, I use intellij but it can import it.

**Comment by KingLemming** [comment]
Given what's going on here now, I think I can safely close this.

**Pull request closed without merging**
